"""模型权威表：以 WorkBuddy 客户端实际下发的模型清单与参数为准。

上游目录接口返回的模型清单与客户端不一致（含已下线的旧模型，且缺少
部分实际可用的新模型），因此这里固化一份与客户端对齐的权威表：
  - 模型清单：具体列出哪些模型可用
  - 参数：倍率 / 默认思考档 / 支持档位 / 可否关闭思考 / 上下文 / 最大输出
  - 能力：是否支持图像、工具调用

各账号的可用模型 = 本表 ∩ 该账号实测结果（探测确认）。
表内 credit 为上游官方倍率；promotions 促销由上游目录的 modelPromotions 补充。
"""

# region -> {model_id: {参数}}
MODELS = {
    "cn": {
        "auto": {
            "name": "Auto",
            "credit": None,
            "default_effort": "high",
            "supported_efforts": [],
            "can_disable_thinking": False,
            "supports_reasoning": True,
            "context_length": 256000,
            "max_output_tokens": 32000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "平衡效果与速度。自动为每个任务匹配最优模型，积分倍率随之浮动",
        },
        "deepseek-v4-flash": {
            "name": "Deepseek-V4-Flash",
            "credit": 0.17,
            "default_effort": "high",
            "supported_efforts": ["low", "high", "xhigh"],
            "can_disable_thinking": True,
            "supports_reasoning": True,
            "context_length": 1000000,
            "max_output_tokens": 50000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "DeepSeek 旗舰模型，支持 1M 上下文窗口",
        },
        "deepseek-v4-pro": {
            "name": "Deepseek-V4-Pro",
            "credit": 0.51,
            "default_effort": "high",
            "supported_efforts": ["low", "high", "xhigh"],
            "can_disable_thinking": True,
            "supports_reasoning": True,
            "context_length": 1000000,
            "max_output_tokens": 393216,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "DeepSeek 旗舰模型，支持 1M 上下文窗口",
        },
        "deepseek-v4.1-flash": {
            "name": "Deepseek-V4.1-Flash",
            "credit": 0.11,
            "default_effort": "high",
            "supported_efforts": ["low", "high", "max"],
            "can_disable_thinking": True,
            "supports_reasoning": True,
            "context_length": 1000000,
            "max_output_tokens": 393216,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "DeepSeek 旗舰模型，支持 1M 上下文窗口，原生多模态",
        },
        "glm-5.1": {
            "name": "GLM-5.1",
            "credit": 0.79,
            "default_effort": "medium",
            "supported_efforts": ["medium"],
            "can_disable_thinking": False,
            "supports_reasoning": True,
            "context_length": 200000,
            "max_output_tokens": 48000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "能力均衡，适合日常使用",
        },
        "glm-5.2": {
            "name": "GLM-5.2",
            "credit": 0.79,
            "default_effort": "high",
            "supported_efforts": ["high", "xhigh"],
            "can_disable_thinking": True,
            "supports_reasoning": True,
            "context_length": 1000000,
            "max_output_tokens": 131072,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "1M 上下文，擅长长程任务",
        },
        "glm-5.3": {
            "name": "GLM-5.3",
            "credit": 0.79,
            "default_effort": "high",
            "supported_efforts": ["low", "high", "max"],
            "can_disable_thinking": True,
            "supports_reasoning": True,
            "context_length": 1000000,
            "max_output_tokens": 131072,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "旗舰模型，擅长复杂软件工程与长程 Agent 任务",
        },
        "glm-5.3-flash": {
            "name": "GLM-5.3-Flash",
            "credit": 0.06,
            "default_effort": "high",
            "supported_efforts": ["low", "high", "max"],
            "can_disable_thinking": True,
            "supports_reasoning": True,
            "context_length": 1000000,
            "max_output_tokens": 131072,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "原生多模态模型，擅长视觉理解与专业任务",
        },
        "glm-5v-turbo": {
            "name": "GLM-5v-Turbo",
            "credit": 0.71,
            "default_effort": "medium",
            "supported_efforts": ["medium"],
            "can_disable_thinking": False,
            "supports_reasoning": True,
            "context_length": 200000,
            "max_output_tokens": 131072,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "原生多模态模型",
        },
        "hy3": {
            "name": "Hy3",
            "credit": 0.0,
            "default_effort": "high",
            "supported_efforts": ["low", "high"],
            "can_disable_thinking": False,
            "supports_reasoning": True,
            "context_length": 192000,
            "max_output_tokens": 64000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "混元思考模型，具有增强的推理能力",
        },
        "hy3-x": {
            "name": "Hy3",
            "credit": 0.05,
            "default_effort": "high",
            "supported_efforts": ["low", "high"],
            "can_disable_thinking": False,
            "supports_reasoning": True,
            "context_length": 192000,
            "max_output_tokens": 64000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "混元思考模型，具有增强的推理能力",
        },
        "hy4-preview": {
            "name": "Hy4 preview",
            "credit": 0.29,
            "default_effort": "high",
            "supported_efforts": ["high"],
            "can_disable_thinking": False,
            "supports_reasoning": True,
            "context_length": 1000000,
            "max_output_tokens": 64000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "混元思考模型，具有增强的推理能力",
        },
        "hy4-preview-f": {
            "name": "Hy4 preview",
            "credit": 0.29,
            "default_effort": "high",
            "supported_efforts": ["high"],
            "can_disable_thinking": False,
            "supports_reasoning": True,
            "context_length": 1000000,
            "max_output_tokens": 64000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "混元思考模型，具有增强的推理能力",
        },
        "kimi-k2.6": {
            "name": "Kimi-K2.6",
            "credit": 0.52,
            "default_effort": "medium",
            "supported_efforts": ["medium"],
            "can_disable_thinking": False,
            "supports_reasoning": True,
            "context_length": 256000,
            "max_output_tokens": 262144,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "多模态模型，适合日常任务",
        },
        "kimi-k2.7": {
            "name": "Kimi-K2.7-Code",
            "credit": 0.57,
            "default_effort": "medium",
            "supported_efforts": ["medium"],
            "can_disable_thinking": False,
            "supports_reasoning": True,
            "context_length": 256000,
            "max_output_tokens": 262144,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "多模态模型，适合日常任务",
        },
        "kimi-k2.8-preview": {
            "name": "Kimi-K2.8-Preview",
            "credit": 0.77,
            "default_effort": "high",
            "supported_efforts": ["low", "high", "max"],
            "can_disable_thinking": True,
            "supports_reasoning": True,
            "context_length": 1000000,
            "max_output_tokens": 64000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "擅长处理复杂的长程自主任务，前端开发能力突出，同时在知识工作与科研推理上表现出色。",
        },
        "kimi-k3-1": {
            "name": "Kimi-K3",
            "credit": 1.62,
            "default_effort": "medium",
            "supported_efforts": ["medium"],
            "can_disable_thinking": False,
            "supports_reasoning": True,
            "context_length": 1000000,
            "max_output_tokens": 1048576,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "擅长处理复杂的长程自主任务，前端开发能力突出，同时在知识工作与科研推理上表现出色。",
        },
        "minimax-m3": {
            "name": "MiniMax-M3",
            "credit": 0.25,
            "default_effort": "medium",
            "supported_efforts": ["medium"],
            "can_disable_thinking": False,
            "supports_reasoning": True,
            "context_length": 512000,
            "max_output_tokens": 524288,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "原生多模态，擅长代码、智能体任务",
        },
    },
    "intl": {
        "auto-chat": {
            "name": "Auto",
            "credit": 0.57,
            "default_effort": "",
            "supported_efforts": [],
            "can_disable_thinking": False,
            "supports_reasoning": False,
            "context_length": 168000,
            "max_output_tokens": 32000,
            "supports_images": False,
            "supports_tool_call": True,
            "description": "智能自动选择模型，适应不同任务需求",
        },
        "balanced-model": {
            "name": "Balanced",
            "credit": 0.59,
            "default_effort": "medium",
            "supported_efforts": ["medium"],
            "can_disable_thinking": False,
            "supports_reasoning": True,
            "context_length": 256000,
            "max_output_tokens": 32000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "速度与质量兼 顾，日常工作首选",
        },
        "deep-model": {
            "name": "Deep",
            "credit": 3.33,
            "default_effort": "",
            "supported_efforts": [],
            "can_disable_thinking": False,
            "supports_reasoning": False,
            "context_length": 176000,
            "max_output_tokens": 24000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "深度推理，适合深度分析与难题",
        },
        "deepseek-v4.1-flash": {
            "name": "Deepseek-V4.1-Flash",
            "credit": 0.0,
            "default_effort": "high",
            "supported_efforts": ["high"],
            "can_disable_thinking": False,
            "supports_reasoning": True,
            "context_length": 1000000,
            "max_output_tokens": 128000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "DeepSeek 旗舰模型，支持 1M 上下文窗口，原生多模态",
        },
        "deepseek-v4.1-flash-sg": {
            "name": "Deepseek-V4.1-Flash",
            "credit": 0.03,
            "default_effort": "high",
            "supported_efforts": [],
            "can_disable_thinking": False,
            "supports_reasoning": True,
            "context_length": 1000000,
            "max_output_tokens": 128000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "DeepSeek 旗舰模型，支持 1M 上下文窗口，原生多模态",
        },
        "default-model": {
            "name": "Auto",
            "credit": None,
            "default_effort": "",
            "supported_efforts": [],
            "can_disable_thinking": False,
            "supports_reasoning": False,
            "context_length": 176000,
            "max_output_tokens": 24000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "优秀的编码模型，适合日常使用",
        },
        "enhance-1.0": {
            "name": "Enhance-1.0",
            "credit": None,
            "default_effort": "",
            "supported_efforts": [],
            "can_disable_thinking": False,
            "supports_reasoning": False,
            "context_length": 1000000,
            "max_output_tokens": 32000,
            "supports_images": False,
            "supports_tool_call": True,
            "description": "性能增强的模型，适用于各种任务",
        },
        "fast-model": {
            "name": "Fast",
            "credit": 0.34,
            "default_effort": "medium",
            "supported_efforts": ["medium"],
            "can_disable_thinking": False,
            "supports_reasoning": True,
            "context_length": 200000,
            "max_output_tokens": 32000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "响应快，适合简单任务",
        },
        "gemini-3.5-flash": {
            "name": "Gemini-3.5-Flash",
            "credit": 0.99,
            "default_effort": "medium",
            "supported_efforts": ["medium"],
            "can_disable_thinking": False,
            "supports_reasoning": True,
            "context_length": 1000000,
            "max_output_tokens": 65536,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "能力均衡，适合日常使用",
        },
        "glm-5.2": {
            "name": "GLM-5.2",
            "credit": 0.79,
            "default_effort": "high",
            "supported_efforts": ["high", "xhigh"],
            "can_disable_thinking": True,
            "supports_reasoning": True,
            "context_length": 1000000,
            "max_output_tokens": 48000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "1M 上下文，擅长长程任务",
        },
        "glm-5.3": {
            "name": "GLM-5.3",
            "credit": 0.79,
            "default_effort": "high",
            "supported_efforts": ["low", "high", "max"],
            "can_disable_thinking": True,
            "supports_reasoning": True,
            "context_length": 1000000,
            "max_output_tokens": 48000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "能力均衡，适合日常使用",
        },
        "glm-5.3-flash": {
            "name": "GLM-5.3-Flash",
            "credit": 0.06,
            "default_effort": "high",
            "supported_efforts": ["low", "high", "max"],
            "can_disable_thinking": True,
            "supports_reasoning": True,
            "context_length": 1000000,
            "max_output_tokens": 32000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "原生多模态模型，擅长视觉理解与专业任务",
        },
        "gpt-5.3-codex": {
            "name": "GPT-5.3-Codex",
            "credit": 1.25,
            "default_effort": "medium",
            "supported_efforts": ["medium"],
            "can_disable_thinking": False,
            "supports_reasoning": True,
            "context_length": 272000,
            "max_output_tokens": 72000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "OpenAI 代码专用模型，非常擅长处理复杂的编码任务",
        },
        "gpt-5.4": {
            "name": "GPT-5.4",
            "credit": 1.65,
            "default_effort": "high",
            "supported_efforts": ["low", "medium", "high", "xhigh"],
            "can_disable_thinking": False,
            "supports_reasoning": True,
            "context_length": 272000,
            "max_output_tokens": 72000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "OpenAI 旗舰编码模型，擅长长程任务",
        },
        "gpt-5.5": {
            "name": "GPT-5.5",
            "credit": 3.31,
            "default_effort": "high",
            "supported_efforts": ["low", "medium", "high", "xhigh"],
            "can_disable_thinking": False,
            "supports_reasoning": True,
            "context_length": 1000000,
            "max_output_tokens": 128000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "OpenAI 旗舰编码模型，擅长长程任务",
        },
        "gpt-5.6-luna": {
            "name": "GPT-5.6-Luna",
            "credit": 0.14,
            "default_effort": "high",
            "supported_efforts": ["low", "medium", "high", "xhigh", "max"],
            "can_disable_thinking": True,
            "supports_reasoning": True,
            "context_length": 1000000,
            "max_output_tokens": 128000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "OpenAI 轻量模型，响应快速，适合日常任务",
        },
        "gpt-5.6-sol": {
            "name": "GPT-5.6-Sol",
            "credit": 3.47,
            "default_effort": "high",
            "supported_efforts": ["low", "medium", "high", "xhigh", "max"],
            "can_disable_thinking": True,
            "supports_reasoning": True,
            "context_length": 1000000,
            "max_output_tokens": 128000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "OpenAI 旗舰模型，擅长复杂推理与长程任务",
        },
        "gpt-5.6-terra": {
            "name": "GPT-5.6-Terra",
            "credit": 1.39,
            "default_effort": "high",
            "supported_efforts": ["low", "medium", "high", "xhigh", "max"],
            "can_disable_thinking": True,
            "supports_reasoning": True,
            "context_length": 1000000,
            "max_output_tokens": 128000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "OpenAI 均衡模型，兼顾能力、速度与成本",
        },
        "gpt-6-astra": {
            "name": "GPT-6-Astra",
            "credit": 6.67,
            "default_effort": "high",
            "supported_efforts": ["low", "medium", "high", "xhigh", "max"],
            "can_disable_thinking": True,
            "supports_reasoning": True,
            "context_length": 1000000,
            "max_output_tokens": 128000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "OpenAI 旗舰模型，擅长复杂推理与长程任务",
        },
        "hy3": {
            "name": "Hy3",
            "credit": 0.0,
            "default_effort": "high",
            "supported_efforts": ["low", "high"],
            "can_disable_thinking": False,
            "supports_reasoning": True,
            "context_length": 192000,
            "max_output_tokens": 64000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "混元思考模型，具有增强的推理能力",
        },
        "hy4-preview": {
            "name": "Hy4 preview",
            "credit": 0.29,
            "default_effort": "high",
            "supported_efforts": ["high"],
            "can_disable_thinking": False,
            "supports_reasoning": True,
            "context_length": 1000000,
            "max_output_tokens": 64000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "混元思考模型，具有增强的推理能力",
        },
        "hy4-preview-f": {
            "name": "hy4-preview-f",
            "credit": None,
            "default_effort": "high",
            "supported_efforts": ["high"],
            "can_disable_thinking": False,
            "supports_reasoning": False,
            "context_length": 1000000,
            "max_output_tokens": None,
            "supports_images": False,
            "supports_tool_call": None,
            "description": "",
        },
        "kimi-k2.6": {
            "name": "Kimi-K2.6",
            "credit": 0.52,
            "default_effort": "medium",
            "supported_efforts": ["medium"],
            "can_disable_thinking": False,
            "supports_reasoning": True,
            "context_length": 256000,
            "max_output_tokens": 32000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "多模态模型，适合日常任务",
        },
        "kimi-k2.8-preview": {
            "name": "Kimi-K2.8-Preview",
            "credit": 0.77,
            "default_effort": "high",
            "supported_efforts": ["low", "high", "max"],
            "can_disable_thinking": True,
            "supports_reasoning": True,
            "context_length": 1000000,
            "max_output_tokens": 32000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "擅长处理复杂的长程自主任务，前端开发能力突出，同时在知识工作与科研推理上表现出色。",
        },
        "kimi-k3": {
            "name": "Kimi-K3",
            "credit": 1.62,
            "default_effort": "medium",
            "supported_efforts": ["medium"],
            "can_disable_thinking": False,
            "supports_reasoning": True,
            "context_length": 1000000,
            "max_output_tokens": 32000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "擅长处理复杂的长程自主任务，前端开发能力突出，同时在知识工作与科研推理上表现出色。",
        },
        "o4-mini": {
            "name": "GPT-4o-Mini",
            "credit": None,
            "default_effort": "",
            "supported_efforts": [],
            "can_disable_thinking": False,
            "supports_reasoning": False,
            "context_length": 104000,
            "max_output_tokens": 24000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "更小、更快的 GPT 模型，适用于日常编码和通用任务",
        },
        "primary-model": {
            "name": "Primary",
            "credit": 3.31,
            "default_effort": "high",
            "supported_efforts": ["high"],
            "can_disable_thinking": False,
            "supports_reasoning": True,
            "context_length": 272000,
            "max_output_tokens": 72000,
            "supports_images": True,
            "supports_tool_call": True,
            "description": "高质量输出，胜任复杂任务",
        },
    },
}


def model_ids(region):
    """某区域的权威模型清单。"""
    return list(MODELS.get(region, {}).keys())


def metadata(region, model_id):
    """某区域某模型的参数；不存在返回 None。"""
    return (MODELS.get(region) or {}).get(model_id)


def find(model_id):
    """跨区域查找模型参数（同 id 可能在两区都有，取任意一个）。"""
    for region in MODELS:
        if model_id in MODELS[region]:
            return MODELS[region][model_id]
    return None
